drop table if exists mensagem;

create table if not exists cliente (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    cpf varchar(14) not null unique,
    senha varchar(255) not null,
    email varchar(160) not null unique,
    data_nascimento date not null
);

create table if not exists endereco (
    id bigint generated by default as identity primary key,
    cliente_id bigint not null,
    cep varchar(9) not null,
    logradouro varchar(160) not null,
    numero varchar(20) not null,
    complemento varchar(120),
    bairro varchar(120) not null,
    cidade varchar(120) not null,
    estado varchar(2) not null,
    pais varchar(80) not null,
    ponto_referencia varchar(160),
    tipo_endereco varchar(40) not null,
    constraint fk_endereco_cliente foreign key (cliente_id) references cliente (id)
);

create index if not exists idx_endereco_cliente_id on endereco (cliente_id);
