create table if not exists adicional (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    produto_id bigint not null,
    constraint fk_adicional_produto foreign key (produto_id) references produto (id) on delete cascade
);

create index if not exists idx_adicional_produto_id on adicional (produto_id);
