create table if not exists pedido (
    id bigint generated by default as identity primary key,
    cliente_id bigint not null,
    produto_id bigint not null,
    endereco_id bigint,
    preco_produto numeric(10, 2) not null,
    valor_total numeric(10, 2) not null,
    status varchar(40) not null,
    criado_em timestamp not null default current_timestamp,
    constraint fk_pedido_cliente foreign key (cliente_id) references cliente (id),
    constraint fk_pedido_produto foreign key (produto_id) references produto (id),
    constraint fk_pedido_endereco foreign key (endereco_id) references endereco (id)
);

create table if not exists pedido_adicional (
    pedido_id bigint not null,
    adicional_id bigint not null,
    preco numeric(10, 2) not null,
    primary key (pedido_id, adicional_id),
    constraint fk_pedido_adicional_pedido foreign key (pedido_id) references pedido (id) on delete cascade,
    constraint fk_pedido_adicional_adicional foreign key (adicional_id) references adicional (id)
);

create index if not exists idx_pedido_cliente_id on pedido (cliente_id);
create index if not exists idx_pedido_adicional_pedido_id on pedido_adicional (pedido_id);
