create table if not exists pedido (
    id bigint generated by default as identity primary key,
    cliente_id bigint not null,
    produto_id bigint not null,
    produto_nome varchar(120) not null,
    endereco_id bigint,
    endereco_resumo varchar(255),
    preco_produto numeric(10, 2) not null,
    valor_total numeric(10, 2) not null,
    status varchar(40) not null,
    criado_em timestamp not null default current_timestamp,
    constraint fk_pedido_cliente foreign key (cliente_id) references cliente (id)
);

create table if not exists pedido_adicional (
    id bigint generated by default as identity primary key,
    pedido_id bigint not null,
    adicional_id bigint,
    adicional_nome varchar(120) not null,
    preco numeric(10, 2) not null,
    constraint fk_pedido_adicional_pedido foreign key (pedido_id) references pedido (id) on delete cascade
);

create index if not exists idx_pedido_cliente_id on pedido (cliente_id);
create index if not exists idx_pedido_adicional_pedido_id on pedido_adicional (pedido_id);
